project_id = "zprqklbasdatmvqgrlgy"

[functions.generate-site]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.generate-logo]
verify_jwt = false

[functions.tools-ai]
verify_jwt = false

[functions.business-plan]
verify_jwt = false

[functions.branding]
verify_jwt = false

[functions.logo-visual]
verify_jwt = false

[functions.regenerate-theme]
verify_jwt = false

[functions.copywriter]
verify_jwt = false
